services:
  redis:
    image: redis:7-alpine
    container_name: youtube-transcript-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - youtube-transcript-network

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: youtube-transcript-api
    restart: unless-stopped
    ports:
      - "5006:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - CACHE_TTL=3600
      - HOST=0.0.0.0
      - PORT=8000
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - youtube-transcript-network

volumes:
  redis_data:
    driver: local

networks:
  youtube-transcript-network:
    driver: bridge